language: node_js

git:
  depth: false

node_js:
  - '10'

cache:
  directories:
    - node_modules

install:
  - npm i -g yarn@1.22.0
  - yarn
  - git remote set-branches --add origin master
  - git fetch

script:
  - yarn lint
  - yarn tdm
  - yarn build

branches:
  except:
    - master

notifications:
  email: false
