language: node_js

node_js:
  - '10'

cache:
  directories:
    - node_modules

install:
  - npm i -g yarn@1.22.0
  - yarn
  - git fetch --unshallow origin master:master
  - git diff origin/master --name-only

script:
  - yarn lint
  - yarn tdm
  - yarn build

branches:
  except:
    - master

notifications:
  email: false
