language: node_js

node_js:
- '10'

cache:
  directories:
  - node_modules

install:
- npm i -g yarn@1.9.1
- yarn install

script:
#- yarn lint
#- yarn test
#- yarn typecheck
- yarn build

sudo: required
services:
  - docker
after_success:
  - bin/docker_push.sh
  - bin/kubernetes_deploy.sh

notifications:
  email: false
