language: node_js

node_js:
  - '10'

cache:
  directories:
    - node_modules

install:
  - npm i -g yarn@1.22.0
  - yarn

before_script:
  - git remote set-branches --add origin master
  - git fetch

script:
  - yarn lint
  - yarn tdm
  - yarn build

notifications:
  email: false
