version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    docker:
      - image: 'cimg/node:14.5.0'
    steps:
      - attach_workspace:
          at: .
      - run: yarn test

  lint:
    docker:
      - image: 'cimg/node:14.5.0'
    steps:
      - attach_workspace:
          at: .
      - run: yarn lint

  typecheck:
    docker:
      - image: 'cimg/node:14.5.0'
    steps:
      - attach_workspace:
          at: .
      - run: yarn typecheck

  build_bundle:
    docker:
      - image: 'cimg/node:14.5.0'
    steps:
      - attach_workspace:
          at: .
      - run: yarn build

  setup:
    docker:
      - image: 'cimg/node:14.5.0'
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - store_artifacts:
          path: yarn.lock
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  node-tests:
    jobs:
      - setup
      - typecheck:
          requires:
           - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
      - build_bundle:
          requires:
            - setup
